### ISSUE TITLE
Integration with Jenkins CI service

### ISSUE THREAD

**Issue by ctranoris** [5GinFIRE/eu.5ginfire.portal.api#33]
This issue tracks the integration progress  with an external CI server based o Jenkins
The end point must be externally configured

**Comment by ctranoris** [comment]
A proposed process is:
1) POST to jenkins endpoint a VNF ID in order to notify it to start a job for VNF validation
q: What is the jenkins endpoint to POST?
2) Jenkins Job must some how authenticate with the portal to retrieve
see the API wiki
3) Jenkins build can GET via API the VNF metadata and archive. For example:
https://portal.5ginfire.eu/5ginfireportal/services/api/repo/vxfs/1

and then the element: 
packageLocation to get the archive from
 "//portal.5ginfire.eu/5ginfireportal/services/api/repo/packages/b751541e-c8ad-4fa1-835f-085acdc29f75/cirros_vnf.tar.gz"

3) After the job completion the result can be updated via PUT method to:
https://portal.5ginfire.eu/5ginfireportal/services/api/repo/admin/vxfs/1
Content-Type: multipart/form-data

Otherwise we can think of other process or endpoints

**Comment by simoreira** [comment]
1. The endpoint to POST would be, for example:  
http://JENKINS_USER_API_TOKEN@ci.5ginfire.eu/job/validation_pipeline&buildWithParameters?token=PIPELINE_TOKEN&VNF_ID=id
where the JENKINS_USER_API_TOKEN is the API token referent to the Jenkins user and the PIPELINE_TOKEN is the job authentication token.

**Comment by ctranoris** [comment]
The defined process is:

1. The portal initiates a validation Job by:
POST to jenkins endpoint a VNF ID in order to notify it to start a job for VNF validation. The endpoint is:
`http://JENKINS_USER_API_TOKEN@ci.5ginfire.eu/job/validation_pipeline&buildWithParameters?token=PIPELINE_TOKEN&VNF_ID=id`
- JENKINS_USER_API_TOKEN will be provided by  Jenkins CI team
- PIPELINE_TOKEN is **provided by ITAV or by the portal?**
- VNF_ID=The VNF ID to fetch.
- JOB_ID=**Will be provided by portal?**

2. Jenkins retrieves the VNF metadata with an X-APIKEY in header:
`curl -v -H "X-APIKEY:ec6a5be8-66bf-4351-e830-"  https://portal.5ginfire.eu/5ginfireportal/services/api/repo/admin/vxfs/VNF_ID` 
The response for example is this:
`
{

  "id": 19,
  "owner": {
    "id": 1,
    "organization": "5GinFIRE",
    "name": "Portal Administrator",
    "email": "xx@xxx",
    "username": "xxuser",
    "active": true,
    "currentSessionID": "cc5c844c-94da-410b-aad2-0d720b2da51f",
    "apikey": null,
    "roles": [
      "PORTALADMIN"
    ]
  },
  "uuid": "eb3ec0c6-ae64-4d13-8ba9-43dfa506b493",
  "name": "rift_ping_vnf",
  "iconsrc": "//portal.5ginfire.eu/5ginfireportal/services/api/repo/images/eb3ec0c6-ae64-4d13-8ba9-43dfa506b493/rift_logo.png",
  "shortDescription": "ping_vnf",
  "longDescription": "This is an example RIFT.ware VNF",
  "version": "1.1",
  "packageLocation": "//portal.5ginfire.eu/5ginfireportal/services/api/repo/packages/eb3ec0c6-ae64-4d13-8ba9-43dfa506b493/ping_vnf_1.1.tar.gz",
  "dateCreated": 1510745958000,
  "dateUpdated": 1531733942000,
  "categories": [
    {
      "id": 2,
      "name": "Networking",
      "appscount": 1,
      "vxFscount": 15,
      "productsCount": 16
    }
  ],
  "extensions": [],
  "screenshots": "",
  "vendor": "RIFT.io",
  "published": true,
  "termsOfUse": null,
  "descriptor": "",
  "descriptorHTML": "..",
  "certified": true,
  "certifiedBy": null,
  "validationStatus": "NOT_STARTED",
  "packagingFormat": "OSMvTWO",
  "supportedMANOPlatforms": [],
  "vxfOnBoardedDescriptors": [ ],
  "vfimagesVDU": [
    {
      "id": 1,
      "name": "cirros034",
      "uuid": "a0ca9c56-3ef5-4a7d-b511-6061d62fa5f2",
      "shortDescription": "Automatically created during vxf cirros_vnfd submission. Owner must update.",
      "packageLocation": "//portal.5ginfire.eu/5ginfireportal/services/api/repo/vfimages/image/a0ca9c56-3ef5-4a7d-b511-6061d62fa5f2/cirros-0.3.4-x86_64-disk.img",
      "publicURL": "https://download.cirros-cloud.net/0.3.4/",
      "dateCreated": 1531732380000,
      "dateUpdated": 1531735718000,
      "refVxFs": [
        {
          "id": 20,
          "name": "rift_pong_vnf"
        }
      ],
      "owner": {
        "id": 1,
        "organization": "5GinFIRE",
        "name": "Portal Administrator",
        "email": "xx@xx.xx.xx",
        "username": "xxuserxx",
        "active": true,
        "currentSessionID": "cc5c844c-94da-410b-aad2-0d720b2da51f",
        "apikey": null,
        "roles": [
          "PORTALADMIN"
        ]
      },
      "published": false,
      "termsOfUse": null,
      "deployedInfrastructures": []
    }
  ]
}`

- X-APIKEY  will be provided by portal team
- The Descriptor file is in element "packageLocation":
- The Image used is also included in vfimagesVDU element in the json "packageLocation":  (if the image is provided by the user and hosted by the portal) or in the "publicURL" element

3. [**UNDER DISCUSSION**] After the job completion the result can be updated via PUT method to :
https://portal.5ginfire.eu/5ginfireportal/services/api/repo/admin/validationjobs/JOB_ID/
PUT payload can be:
{
  "vnfid": 19,
  "validation_status": true **(or false),**
  "jenkins_output_log": "http://ci.5ginfire.eu/jobs...."
}

- JOB_ID must be the same as the original send

**Comment by simoreira** [comment]
1. The PIPELINE_TOKEN as well as the JOB_ID are generated by Jenkins. The first corresponds to an unique token that identifies the pipeline and the second is generated whenever a job is triggered. 

2. Can you please provide me a X-APIKEY so I can test the pipeline?

**Comment by ctranoris** [comment]
We need an example POST request and its response.

**Comment by simoreira** [comment]
The POST request is made directly to Jenkins through this endpoint:

[http://5ginfire:JENKINS_USER_API_TOKEN@ci.5ginfire.eu/job/validation_pipeline/buildWithParameters?token=PIPELINE_TOKEN&VNF_ID=vnf_id](http://5ginfire:JENKINS_USER_API_TOKEN@ci.5ginfire.eu/job/validation_pipeline/buildWithParameters?token=PIPELINE_TOKEN&VNF_ID=vnf_id)

Therefore, only the VNF_ID should be inserted.

We will provide you the JENKINS_USER_API_TOKEN and the PIPELINE_TOKEN.

As for the response, according to the Jenkins syntax, we will not have a JOB_ID but actually a BUILD_ID (since the JOB is the pipeline).

In this way, the response layout is:
```
{
"vnfd_id": 1, 
"build_id": 133 
"validation_status": true (or false), 
"jenkins_output_log": "http://localhost:8080/job/Validation%20Pipeline/133/api/json"
}
```

**Comment by ctranoris** [comment]
The Integration tests completed successfully today at the production system of the portal
Now whenever there is a New uploaded VNF,
or someone updates the descriptor of a VNF the Validation job is also triggered.
An issue is also created in Bugzilla as before, as well as when the result job finishes.
If validation is successful, the VxF is marked as  "Certified".
In future, an automated ONBOARDING to OSM will be also triggered.
